package com.tinqa.procurement.product.dto;

import com.tinqa.procurement.item.dto.ItemDTOs;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class ProductDTOs {

    @Getter
    @Setter
    public static class CreateRequest {
        // Optional: generated by the backend when not supplied
        @Size(max = 50, message = "Product ID cannot exceed 50 characters")
        @Pattern(regexp = "^[A-Za-z0-9_-]*$", message = "Product ID can only contain letters, digits, '-' and '_'")
        private String productId;

        @NotNull(message = "Item ID is required")
        private Long itemId;

        @NotNull(message = "Quantity is required")
        @Positive(message = "Quantity must be greater than zero")
        @Digits(integer = 11, fraction = 3, message = "Quantity can have at most 11 digits and 3 decimal places")
        private BigDecimal quantity;
    }

    // Item and quantity are fixed once stock has been consumed; delete and recreate the product to change them
    @Getter
    @Setter
    public static class UpdateRequest {
        @NotNull(message = "Active status is required")
        private Boolean isActive;
    }

    @Getter
    @Setter
    public static class Response {
        private Long id;
        private String productId;
        private Long itemId;
        private String itemName;
        private String itemSku;
        private String unitOfMeasure;
        private BigDecimal quantity;
        private List<StockAllocationResponse> stockAllocations;
        private List<ItemDTOs.WarrantyResponse> itemWarranties;
        private Boolean isActive;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
        private Long createdBy;
        private Long updatedBy;
    }

    @Getter
    @Setter
    public static class StockAllocationResponse {
        private Long stockId;
        private String stockIdentityNumber;
        private String batchNumber;
        private BigDecimal quantity;
    }
}
