package com.tinqa.procurement.stock.service.impl;

import com.tinqa.procurement.common.enums.ApprovalStatus;
import com.tinqa.procurement.common.exception.BadRequestException;
import com.tinqa.procurement.common.exception.ResourceNotFoundException;
import com.tinqa.procurement.dealer.entity.Dealer;
import com.tinqa.procurement.dealer.repository.DealerRepository;
import com.tinqa.procurement.item.entity.Item;
import com.tinqa.procurement.item.repository.ItemRepository;
import com.tinqa.procurement.notification.service.NotificationService;
import com.tinqa.procurement.order.entity.Order;
import com.tinqa.procurement.order.repository.OrderRepository;
import com.tinqa.procurement.security.model.User;
import com.tinqa.procurement.security.repository.UserRepository;
import com.tinqa.procurement.stock.dto.StockDTOs;
import com.tinqa.procurement.stock.entity.Stock;
import com.tinqa.procurement.stock.repository.StockRepository;
import com.tinqa.procurement.stock.service.StockService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class StockServiceImpl implements StockService {

    private final StockRepository stockRepository;
    private final OrderRepository orderRepository;
    private final DealerRepository dealerRepository;
    private final ItemRepository itemRepository;
    private final NotificationService notificationService;
    private final UserRepository userRepository;

    @Override
    @Transactional
    public StockDTOs.Response createStockFromOrder(StockDTOs.CreateFromOrderRequest request, Long currentUserId) {
        Order order = orderRepository.findByOrderNumber(request.getOrderNumber())
                .orElseThrow(() -> new ResourceNotFoundException("Order not found with number: " + request.getOrderNumber()));

        if (request.getUnitsPassedTest().add(request.getDefectedUnits()).compareTo(order.getOrderQuantity()) > 0) {
            throw new BadRequestException("Passed + defected units cannot exceed original total order quantity (" + order.getOrderQuantity() + ")");
        }

        String stockIdentityNumber = "STK-" + System.currentTimeMillis() + "-" + UUID.randomUUID().toString().substring(0, 5).toUpperCase();

        // Auto-generate a guaranteed unique batch number
        // Format: BATCH-YYYYMMDD-<ORDER_ID>-<5_CHAR_UUID>
        String datePrefix = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.BASIC_ISO_DATE);
        String uniqueSuffix = UUID.randomUUID().toString().substring(0, 5).toUpperCase();
        String autoGeneratedBatchNumber = String.format("BAT-%s-%d-%s", datePrefix, order.getId(), uniqueSuffix);

        Stock stock = Stock.builder()
                .stockIdentityNumber(stockIdentityNumber)
                .batchNumber(autoGeneratedBatchNumber)
                .order(order)
                .dealer(order.getDealer())
                .item(order.getItem())
                .unitsPassedTest(order.getOrderQuantity())
                .defectedUnits(request.getDefectedUnits())
                .availableUnits(order.getOrderQuantity())
                .hasTested(request.getHasTested())
                .additionalInfo(request.getAdditionalInfo())
                .approvalStatus(ApprovalStatus.PENDING)
                .dateOfArrival(request.getDateOfArrival())
                .createdBy(currentUserId)
                .updatedBy(currentUserId)
                .build();

        return mapToResponse(stockRepository.save(stock));
    }

    @Override
    @Transactional
    public StockDTOs.Response addStockQuantity(Long id, StockDTOs.QuantityAdjustmentRequest request, Long currentUserId) {
        Stock stock = getValidatedStock(id);

        stock.setUnitsPassedTest(stock.getUnitsPassedTest().add(request.getQuantity()));
        stock.setAvailableUnits(stock.getAvailableUnits().add(request.getQuantity()));
        stock.setUpdatedBy(currentUserId);

        return mapToResponse(stockRepository.save(stock));
    }

    @Override
    @Transactional
    public StockDTOs.Response reduceStockQuantity(Long id, StockDTOs.QuantityAdjustmentRequest request, Long currentUserId) {
        Stock stock = getValidatedStock(id);

        if (stock.getAvailableUnits().compareTo(request.getQuantity()) < 0) {
            throw new BadRequestException("Insufficient stock available. Current available: " + stock.getAvailableUnits());
        }

        stock.setAvailableUnits(stock.getAvailableUnits().subtract(request.getQuantity()));
        stock.setUpdatedBy(currentUserId);

        return mapToResponse(stockRepository.save(stock));
    }

    @Override
    @Transactional
    public StockDTOs.Response processAdminL2Approval(Long id, StockDTOs.ApprovalDecisionRequest request, Long adminUserId) {
        Stock stock = stockRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Stock entry not found with id: " + id));

        if (stock.getApprovalStatus() != ApprovalStatus.PENDING) {
            throw new BadRequestException("Stock request processed already with status: " + stock.getApprovalStatus());
        }

        User user = userRepository.findById(adminUserId)
                .orElseThrow(() -> new ResourceNotFoundException("User entry not found with id: " + id));

        if(!stock.getUpdatedBy().equals(adminUserId)) {
            String title = "Stock Approved";
            String message = "Stock Batch " + stock.getBatchNumber() + " approved by ID: " + user.getUsername() + ".";
            if (request.getDecision() == ApprovalStatus.REJECTED) {
                title = "Stock Cancelled";
                message = "Stock Batch: " + stock.getBatchNumber() + " cancelled by ID: " + user.getUsername() + ". Reason: " + request.getRejectionReason();
            }
            notificationService.createForUser(stock.getUpdatedBy(), title, message);
        }
        stock.setApprovalStatus(request.getDecision());
        stock.setApprovedBy(adminUserId);
        stock.setApprovedAt(LocalDateTime.now());

        if (request.getDecision() == ApprovalStatus.REJECTED) {
            stock.setRejectionReason(request.getRejectionReason());
            stock.setAvailableUnits(BigDecimal.ZERO);
        }
        return mapToResponse(stockRepository.save(stock));
    }

    @Override
    @Transactional(readOnly = true)
    public StockDTOs.Response getStockById(Long id) {
        Stock stock = stockRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Stock entry not found with id: " + id));
        return mapToResponse(stock);
    }

    @Override
    @Transactional(readOnly = true)
    public List<StockDTOs.Response> getAllStocks() {
        return stockRepository.findAll().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<StockDTOs.Response> getAllStocksByStatus(ApprovalStatus status) {
        return stockRepository.findByApprovalStatus(status).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }


    private Stock getValidatedStock(Long id) {
        Stock stock = stockRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Stock entry not found with id: " + id));
        if (stock.getApprovalStatus() != ApprovalStatus.APPROVED) {
            throw new BadRequestException("Stock operations are restricted to approved stock entries.");
        }
        return stock;
    }

    private StockDTOs.Response mapToResponse(Stock stock) {
        Order order = stock.getOrder();
        return StockDTOs.Response.builder()
                .id(stock.getId())
                .stockIdentityNumber(stock.getStockIdentityNumber())
                .batchNumber(stock.getBatchNumber())
                .orderNumber(order.getOrderNumber())
                .dealerId(stock.getDealer().getId())
                .dealerName(stock.getDealer().getName())
                .itemId(stock.getItem().getId())
                .itemName(stock.getItem().getName())
                .totalOrderQuantity(order.getOrderQuantity())
                .unitType(order.getUnitType())
                .unitsPassedTest(stock.getUnitsPassedTest())
                .defectedUnits(stock.getDefectedUnits())
                .availableUnits(stock.getAvailableUnits())
                .unitPrice(order.getUnitPrice())
                .totalPrice(order.getTotalPrice())
                .hasTested(stock.getHasTested())
                .additionalInfo(stock.getAdditionalInfo())
                .approvalStatus(stock.getApprovalStatus())
                .approvedBy(stock.getApprovedBy())
                .approvedAt(stock.getApprovedAt())
                .rejectionReason(stock.getRejectionReason())
                .dateOfArrival(stock.getDateOfArrival())
                .isActive(stock.getIsActive())
                .createdAt(stock.getCreatedAt())
                .createdBy(stock.getCreatedBy())
                .build();
    }

    @Transactional
    public StockDTOs.Response updateStock(Long id, StockDTOs.UpdateRequest request, Long currentUserId) {
        Stock stock = stockRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Stock not found with id: " + id));

        // Update Dealer if changed
        if (!stock.getDealer().getId().equals(request.getDealerId())) {
            Dealer dealer = dealerRepository.findById(request.getDealerId())
                    .orElseThrow(() -> new ResourceNotFoundException("Dealer not found with id: " + request.getDealerId()));
            stock.setDealer(dealer);
        }

        // Update Item if changed
        if (!stock.getItem().getId().equals(request.getItemId())) {
            Item item = itemRepository.findById(request.getItemId())
                    .orElseThrow(() -> new ResourceNotFoundException("Item not found with id: " + request.getItemId()));
            stock.setItem(item);
        }

        stock.setBatchNumber(request.getBatchNumber());
        stock.setUnitsPassedTest(request.getUnitsPassedTest());
        stock.setDefectedUnits(request.getDefectedUnits());

        // Automatically manage availableUnits based on unitsPassed (or keep your custom business logic)
        stock.setAvailableUnits(request.getUnitsPassedTest());

        stock.setHasTested(request.getHasTested());
        stock.setDateOfArrival(request.getDateOfArrival());
        stock.setAdditionalInfo(request.getAdditionalInfo());

        if (request.getIsActive() != null) {
            stock.setIsActive(request.getIsActive());
        }

        stock.setUpdatedBy(currentUserId);

        Stock updatedStock = stockRepository.save(stock);
        return mapToResponse(updatedStock);
    }
}