spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tinqa_procurement
    username: tinqa_app
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.tinqa.procurement: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG