package com.tinqa.procurement.document.constant;

public enum DocumentPurpose {

    PROFILE_DOCUMENT,
    KYC_VERIFICATION,
    BUSINESS_DOCUMENT,
    WORKSHOP_DOCUMENT,

    PRODUCT_PRE_MANUFACTURING,
    PRODUCT_DURING_MANUFACTURING,
    PRODUCT_POST_MANUFACTURING,

    INSPECTION_DOCUMENT,
    INSPECTION_PHOTO,

    AUCTION_DOCUMENT,
    ORDER_DOCUMENT,

    INVOICE,
    CERTIFICATE,

    CONTRACT,
    CLAIM_EVIDENCE,
    OTHER
}