CREATE TABLE specification_definition (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          item_type_id BIGINT NOT NULL,
                                          code VARCHAR(50) NOT NULL,
                                          name VARCHAR(100) NOT NULL,
                                          description VARCHAR(500),
                                          data_type VARCHAR(20) NOT NULL,
                                          unit VARCHAR(20),
                                          required BOOLEAN NOT NULL DEFAULT FALSE,
                                          min_value DECIMAL(15,4),
                                          max_value DECIMAL(15,4),
                                          active BOOLEAN NOT NULL DEFAULT TRUE,
                                          display_order INT NOT NULL DEFAULT 0,
                                          created_at TIMESTAMP NOT NULL,
                                          updated_at TIMESTAMP NOT NULL,
                                          PRIMARY KEY (id),
                                          CONSTRAINT uk_specification_definition_type_code
                                              UNIQUE (item_type_id, code),
                                          CONSTRAINT fk_specification_definition_item_type
                                              FOREIGN KEY (item_type_id) REFERENCES item_type(id)
);

CREATE INDEX idx_specification_definition_item_type_id
    ON specification_definition(item_type_id);

CREATE INDEX idx_specification_definition_active
    ON specification_definition(active);

CREATE TABLE specification_option (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      specification_definition_id BIGINT NOT NULL,
                                      code VARCHAR(50) NOT NULL,
                                      name VARCHAR(100) NOT NULL,
                                      display_order INT NOT NULL DEFAULT 0,
                                      active BOOLEAN NOT NULL DEFAULT TRUE,
                                      created_at TIMESTAMP NOT NULL,
                                      updated_at TIMESTAMP NOT NULL,
                                      PRIMARY KEY (id),
                                      CONSTRAINT uk_specification_option_definition_code
                                          UNIQUE (specification_definition_id, code),
                                      CONSTRAINT fk_specification_option_definition
                                          FOREIGN KEY (specification_definition_id)
                                              REFERENCES specification_definition(id)
);

CREATE INDEX idx_specification_option_definition_id
    ON specification_option(specification_definition_id);

CREATE INDEX idx_specification_option_active
    ON specification_option(active);

CREATE TABLE item_specification_value (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          item_id BIGINT NOT NULL,
                                          specification_definition_id BIGINT NOT NULL,
                                          string_value VARCHAR(1000),
                                          numeric_value DECIMAL(15,4),
                                          boolean_value BOOLEAN,
                                          date_value DATE,
                                          option_id BIGINT,
                                          created_at TIMESTAMP NOT NULL,
                                          updated_at TIMESTAMP NOT NULL,
                                          PRIMARY KEY (id),
                                          CONSTRAINT uk_item_specification_item_definition
                                              UNIQUE (item_id, specification_definition_id),
                                          CONSTRAINT fk_item_specification_item
                                              FOREIGN KEY (item_id) REFERENCES item(id),
                                          CONSTRAINT fk_item_specification_definition
                                              FOREIGN KEY (specification_definition_id)
                                                  REFERENCES specification_definition(id),
                                          CONSTRAINT fk_item_specification_option
                                              FOREIGN KEY (option_id) REFERENCES specification_option(id)
);

CREATE INDEX idx_item_specification_value_item_id
    ON item_specification_value(item_id);

CREATE INDEX idx_item_specification_value_definition_id
    ON item_specification_value(specification_definition_id);

CREATE INDEX idx_item_specification_value_option_id
    ON item_specification_value(option_id);