CREATE TABLE procurement_request (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     request_number VARCHAR(50) NOT NULL,
                                     title VARCHAR(200) NOT NULL,
                                     description VARCHAR(2000),
                                     requested_by BIGINT NOT NULL,
                                     status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                                     priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
                                     required_by DATE,
                                     created_at TIMESTAMP NOT NULL,
                                     updated_at TIMESTAMP NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT uk_procurement_request_number UNIQUE (request_number),
                                     CONSTRAINT fk_procurement_request_requested_by
                                         FOREIGN KEY (requested_by) REFERENCES users(id)
);

CREATE INDEX idx_procurement_request_requested_by
    ON procurement_request(requested_by);

CREATE INDEX idx_procurement_request_status
    ON procurement_request(status);

CREATE INDEX idx_procurement_request_priority
    ON procurement_request(priority);

CREATE INDEX idx_procurement_request_required_by
    ON procurement_request(required_by);


CREATE TABLE procurement_request_item (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          procurement_request_id BIGINT NOT NULL,
                                          item_id BIGINT NOT NULL,
                                          quantity DECIMAL(15,4) NOT NULL,
                                          unit_of_measure VARCHAR(30) NOT NULL,
                                          specification_notes VARCHAR(2000),
                                          required_by DATE,
                                          created_at TIMESTAMP NOT NULL,
                                          updated_at TIMESTAMP NOT NULL,
                                          PRIMARY KEY (id),
                                          CONSTRAINT fk_procurement_request_item_request
                                              FOREIGN KEY (procurement_request_id)
                                                  REFERENCES procurement_request(id),
                                          CONSTRAINT fk_procurement_request_item_item
                                              FOREIGN KEY (item_id)
                                                  REFERENCES item(id)
);

CREATE INDEX idx_procurement_request_item_request_id
    ON procurement_request_item(procurement_request_id);

CREATE INDEX idx_procurement_request_item_item_id
    ON procurement_request_item(item_id);