CREATE TABLE quotation (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           quotation_number VARCHAR(50) NOT NULL,
                           procurement_request_id BIGINT NOT NULL,
                           dealer_id BIGINT NOT NULL,
                           workshop_id BIGINT NOT NULL,
                           submitted_at TIMESTAMP,
                           valid_until DATE,
                           status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                           remarks VARCHAR(2000),
                           created_at TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP NOT NULL,
                           PRIMARY KEY (id),

                           CONSTRAINT uk_quotation_number
                               UNIQUE (quotation_number),

                           CONSTRAINT fk_quotation_procurement_request
                               FOREIGN KEY (procurement_request_id)
                                   REFERENCES procurement_request(id),

                           CONSTRAINT fk_quotation_dealer
                               FOREIGN KEY (dealer_id)
                                   REFERENCES dealer(id),

                           CONSTRAINT fk_quotation_workshop
                               FOREIGN KEY (workshop_id)
                                   REFERENCES workshop(id)
);

CREATE INDEX idx_quotation_procurement_request_id
    ON quotation(procurement_request_id);

CREATE INDEX idx_quotation_dealer_id
    ON quotation(dealer_id);

CREATE INDEX idx_quotation_workshop_id
    ON quotation(workshop_id);

CREATE INDEX idx_quotation_status
    ON quotation(status);


CREATE TABLE quotation_item (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                quotation_id BIGINT NOT NULL,
                                procurement_request_item_id BIGINT NOT NULL,
                                item_id BIGINT NOT NULL,

                                quantity DECIMAL(15,4) NOT NULL,
                                unit_of_measure VARCHAR(30) NOT NULL,

                                unit_price DECIMAL(15,2) NOT NULL,
                                discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
                                tax_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
                                tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
                                total_amount DECIMAL(15,2) NOT NULL,

                                delivery_days INT,
                                remarks VARCHAR(2000),

                                created_at TIMESTAMP NOT NULL,
                                updated_at TIMESTAMP NOT NULL,

                                PRIMARY KEY (id),

                                CONSTRAINT fk_quotation_item_quotation
                                    FOREIGN KEY (quotation_id)
                                        REFERENCES quotation(id),

                                CONSTRAINT fk_quotation_item_request_item
                                    FOREIGN KEY (procurement_request_item_id)
                                        REFERENCES procurement_request_item(id),

                                CONSTRAINT fk_quotation_item_item
                                    FOREIGN KEY (item_id)
                                        REFERENCES item(id)
);

CREATE INDEX idx_quotation_item_quotation_id
    ON quotation_item(quotation_id);

CREATE INDEX idx_quotation_item_request_item_id
    ON quotation_item(procurement_request_item_id);

CREATE INDEX idx_quotation_item_item_id
    ON quotation_item(item_id);