CREATE TABLE auction (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         auction_number VARCHAR(50) NOT NULL,
                         procurement_request_id BIGINT NOT NULL,

                         title VARCHAR(200) NOT NULL,
                         description VARCHAR(2000),

                         auction_type VARCHAR(20) NOT NULL DEFAULT 'REVERSE',
                         status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

                         start_time TIMESTAMP,
                         end_time TIMESTAMP,

                         minimum_bid_amount DECIMAL(15,2),
                         bid_increment DECIMAL(15,2),

                         currency VARCHAR(10) NOT NULL DEFAULT 'INR',

                         created_by BIGINT NOT NULL,

                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP NOT NULL,

                         PRIMARY KEY (id),

                         CONSTRAINT uk_auction_number
                             UNIQUE (auction_number),

                         CONSTRAINT fk_auction_procurement_request
                             FOREIGN KEY (procurement_request_id)
                                 REFERENCES procurement_request(id),

                         CONSTRAINT fk_auction_created_by
                             FOREIGN KEY (created_by)
                                 REFERENCES users(id)
);

CREATE INDEX idx_auction_procurement_request_id
    ON auction(procurement_request_id);

CREATE INDEX idx_auction_status
    ON auction(status);

CREATE INDEX idx_auction_start_time
    ON auction(start_time);

CREATE INDEX idx_auction_end_time
    ON auction(end_time);

CREATE INDEX idx_auction_created_by
    ON auction(created_by);