CREATE TABLE auction_item (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              auction_id BIGINT NOT NULL,
                              procurement_request_item_id BIGINT NOT NULL,

                              quantity DECIMAL(15,4) NOT NULL,
                              unit_of_measure VARCHAR(30) NOT NULL,

                              starting_price DECIMAL(15,2),
                              minimum_price DECIMAL(15,2),

                              created_at TIMESTAMP NOT NULL,
                              updated_at TIMESTAMP NOT NULL,

                              PRIMARY KEY (id),

                              CONSTRAINT fk_auction_item_auction
                                  FOREIGN KEY (auction_id)
                                      REFERENCES auction(id),

                              CONSTRAINT fk_auction_item_request_item
                                  FOREIGN KEY (procurement_request_item_id)
                                      REFERENCES procurement_request_item(id),

                              CONSTRAINT uk_auction_item_request_item
                                  UNIQUE (auction_id, procurement_request_item_id)
);

CREATE INDEX idx_auction_item_auction_id
    ON auction_item(auction_id);

CREATE INDEX idx_auction_item_request_item_id
    ON auction_item(procurement_request_item_id);

CREATE TABLE auction_participant (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     auction_id BIGINT NOT NULL,
                                     dealer_id BIGINT NOT NULL,
                                     quotation_id BIGINT,

                                     status VARCHAR(20) NOT NULL DEFAULT 'INVITED',

                                     invited_at TIMESTAMP,
                                     accepted_at TIMESTAMP,

                                     created_at TIMESTAMP NOT NULL,
                                     updated_at TIMESTAMP NOT NULL,

                                     PRIMARY KEY (id),

                                     CONSTRAINT fk_auction_participant_auction
                                         FOREIGN KEY (auction_id)
                                             REFERENCES auction(id),

                                     CONSTRAINT fk_auction_participant_dealer
                                         FOREIGN KEY (dealer_id)
                                             REFERENCES dealer(id),

                                     CONSTRAINT fk_auction_participant_quotation
                                         FOREIGN KEY (quotation_id)
                                             REFERENCES quotation(id),

                                     CONSTRAINT uk_auction_participant_dealer
                                         UNIQUE (auction_id, dealer_id)
);

CREATE INDEX idx_auction_participant_auction_id
    ON auction_participant(auction_id);

CREATE INDEX idx_auction_participant_dealer_id
    ON auction_participant(dealer_id);

CREATE INDEX idx_auction_participant_quotation_id
    ON auction_participant(quotation_id);

CREATE INDEX idx_auction_participant_status
    ON auction_participant(status);