CREATE TABLE auction_bid (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                             auction_id BIGINT NOT NULL,
                             auction_item_id BIGINT NOT NULL,
                             auction_participant_id BIGINT NOT NULL,

                             bid_sequence BIGINT NOT NULL,
                             bid_amount DECIMAL(15,2) NOT NULL,

                             bid_time TIMESTAMP NOT NULL,

                             created_at TIMESTAMP NOT NULL,

                             PRIMARY KEY (id),

                             CONSTRAINT fk_auction_bid_auction
                                 FOREIGN KEY (auction_id)
                                     REFERENCES auction(id),

                             CONSTRAINT fk_auction_bid_auction_item
                                 FOREIGN KEY (auction_item_id)
                                     REFERENCES auction_item(id),

                             CONSTRAINT fk_auction_bid_participant
                                 FOREIGN KEY (auction_participant_id)
                                     REFERENCES auction_participant(id),

                             CONSTRAINT uk_auction_bid_sequence
                                 UNIQUE (auction_id, bid_sequence)
);

CREATE INDEX idx_auction_bid_auction_id
    ON auction_bid(auction_id);

CREATE INDEX idx_auction_bid_auction_item_id
    ON auction_bid(auction_item_id);

CREATE INDEX idx_auction_bid_participant_id
    ON auction_bid(auction_participant_id);

CREATE INDEX idx_auction_bid_bid_time
    ON auction_bid(bid_time);