CREATE TABLE auction_award (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                               auction_id BIGINT NOT NULL,
                               auction_participant_id BIGINT NOT NULL,
                               winning_bid_id BIGINT NOT NULL,

                               status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                               awarded_by BIGINT,
                               awarded_at TIMESTAMP,

                               award_amount DECIMAL(15,2) NOT NULL,

                               remarks VARCHAR(2000),

                               created_at TIMESTAMP NOT NULL,
                               updated_at TIMESTAMP NOT NULL,

                               PRIMARY KEY (id),

                               CONSTRAINT uk_auction_award_auction
                                   UNIQUE (auction_id),

                               CONSTRAINT fk_auction_award_auction
                                   FOREIGN KEY (auction_id)
                                       REFERENCES auction(id),

                               CONSTRAINT fk_auction_award_participant
                                   FOREIGN KEY (auction_participant_id)
                                       REFERENCES auction_participant(id),

                               CONSTRAINT fk_auction_award_winning_bid
                                   FOREIGN KEY (winning_bid_id)
                                       REFERENCES auction_bid(id),

                               CONSTRAINT fk_auction_award_awarded_by
                                   FOREIGN KEY (awarded_by)
                                       REFERENCES users(id)
);

CREATE INDEX idx_auction_award_participant_id
    ON auction_award(auction_participant_id);

CREATE INDEX idx_auction_award_winning_bid_id
    ON auction_award(winning_bid_id);

CREATE INDEX idx_auction_award_awarded_by
    ON auction_award(awarded_by);

CREATE INDEX idx_auction_award_status
    ON auction_award(status);