CREATE TABLE project (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                         project_code VARCHAR(50) NOT NULL,
                         name VARCHAR(200) NOT NULL,
                         description VARCHAR(3000),

                         status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

                         start_date DATE,
                         target_completion_date DATE,
                         actual_completion_date DATE,

                         created_by BIGINT NOT NULL,

                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP NOT NULL,

                         PRIMARY KEY (id),

                         CONSTRAINT uk_project_code
                             UNIQUE (project_code),

                         CONSTRAINT fk_project_created_by
                             FOREIGN KEY (created_by)
                                 REFERENCES users(id)
);

CREATE INDEX idx_project_status
    ON project(status);

CREATE INDEX idx_project_created_by
    ON project(created_by);

CREATE INDEX idx_project_target_completion_date
    ON project(target_completion_date);