CREATE TABLE workshop_capability (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                                     workshop_id BIGINT NOT NULL,
                                     item_type_id BIGINT NOT NULL,

                                     active BOOLEAN NOT NULL DEFAULT TRUE,

                                     approved BOOLEAN NOT NULL DEFAULT FALSE,

                                     approved_by BIGINT,
                                     approved_at TIMESTAMP,

                                     created_at TIMESTAMP NOT NULL,
                                     updated_at TIMESTAMP NOT NULL,

                                     PRIMARY KEY (id),

                                     CONSTRAINT fk_workshop_capability_workshop
                                         FOREIGN KEY (workshop_id)
                                             REFERENCES workshop(id),

                                     CONSTRAINT fk_workshop_capability_item_type
                                         FOREIGN KEY (item_type_id)
                                             REFERENCES item_type(id),

                                     CONSTRAINT fk_workshop_capability_approved_by
                                         FOREIGN KEY (approved_by)
                                             REFERENCES users(id),

                                     CONSTRAINT uk_workshop_capability
                                         UNIQUE (workshop_id, item_type_id)
);

CREATE INDEX idx_workshop_capability_workshop_id
    ON workshop_capability(workshop_id);

CREATE INDEX idx_workshop_capability_item_type_id
    ON workshop_capability(item_type_id);

CREATE INDEX idx_workshop_capability_active_approved
    ON workshop_capability(active, approved);