CREATE TABLE employee_profile_change_request (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                                                 employee_id BIGINT NOT NULL,

                                                 requested_by BIGINT NOT NULL,

                                                 reviewed_by BIGINT,

                                                 request_type VARCHAR(50) NOT NULL DEFAULT 'PROFILE_UPDATE',

                                                 current_values JSONB NOT NULL,

                                                 requested_values JSONB NOT NULL,

                                                 status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

                                                 requester_remarks VARCHAR(500),

                                                 reviewer_remarks VARCHAR(500),

                                                 requested_at TIMESTAMP NOT NULL,

                                                 reviewed_at TIMESTAMP,

                                                 created_at TIMESTAMP NOT NULL,

                                                 updated_at TIMESTAMP NOT NULL,

                                                 PRIMARY KEY (id),

                                                 CONSTRAINT fk_profile_change_employee
                                                     FOREIGN KEY (employee_id)
                                                         REFERENCES employee(id),

                                                 CONSTRAINT fk_profile_change_requested_by
                                                     FOREIGN KEY (requested_by)
                                                         REFERENCES users(id),

                                                 CONSTRAINT fk_profile_change_reviewed_by
                                                     FOREIGN KEY (reviewed_by)
                                                         REFERENCES users(id),

                                                 CONSTRAINT chk_profile_change_status
                                                     CHECK (
                                                         status IN (
                                                                    'PENDING',
                                                                    'APPROVED',
                                                                    'REJECTED',
                                                                    'CANCELLED'
                                                             )
                                                         )
);

CREATE INDEX idx_profile_change_employee
    ON employee_profile_change_request(employee_id);

CREATE INDEX idx_profile_change_status
    ON employee_profile_change_request(status);

CREATE INDEX idx_profile_change_requested_by
    ON employee_profile_change_request(requested_by);

CREATE INDEX idx_profile_change_reviewed_by
    ON employee_profile_change_request(reviewed_by);

CREATE INDEX idx_profile_change_employee_status
    ON employee_profile_change_request(employee_id, status);