-- Employee Profile Change Approval Workflow
CREATE TABLE employee_profile_change_request (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 employee_id BIGINT NOT NULL,
                                                 requested_by BIGINT NOT NULL,
                                                 reviewed_by BIGINT,
                                                 approved_by BIGINT,                   -- <--- Added missing column

    -- Profile Field Payload
                                                 first_name VARCHAR(100),
                                                 middle_name VARCHAR(100),
                                                 last_name VARCHAR(100),
                                                 display_name VARCHAR(200),
                                                 date_of_birth DATE,
                                                 gender VARCHAR(20),
                                                 department VARCHAR(100),
                                                 designation VARCHAR(100),
                                                 personal_email VARCHAR(255),
                                                 primary_phone VARCHAR(20),
                                                 alternate_phone VARCHAR(20),

    -- Workflow & Audit Details
                                                 request_type VARCHAR(50) NOT NULL DEFAULT 'PROFILE_UPDATE',
                                                 current_values JSONB NOT NULL DEFAULT '{}'::jsonb,
                                                 requested_values JSONB NOT NULL DEFAULT '{}'::jsonb,
                                                 status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                                                 requester_remarks VARCHAR(500),
                                                 reviewer_remarks VARCHAR(500),
                                                 rejection_reason VARCHAR(500),

    -- Timestamps
                                                 requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 reviewed_at TIMESTAMP,
                                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Foreign Key Constraints
                                                 CONSTRAINT fk_profile_change_employee FOREIGN KEY (employee_id) REFERENCES employee(id),
                                                 CONSTRAINT fk_profile_change_requested_by FOREIGN KEY (requested_by) REFERENCES users(id),
                                                 CONSTRAINT fk_profile_change_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id),
                                                 CONSTRAINT fk_profile_change_approved_by FOREIGN KEY (approved_by) REFERENCES users(id), -- <--- Added FK constraint
                                                 CONSTRAINT chk_profile_change_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

-- Indexes for Fast Querying
CREATE INDEX idx_profile_change_employee ON employee_profile_change_request(employee_id);
CREATE INDEX idx_profile_change_status ON employee_profile_change_request(status);
CREATE INDEX idx_profile_change_requested_by ON employee_profile_change_request(requested_by);
CREATE INDEX idx_profile_change_employee_status ON employee_profile_change_request(employee_id, status);