CREATE TABLE dealer (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        user_id BIGINT NOT NULL,
                        dealer_code VARCHAR(50) NOT NULL,
                        business_type VARCHAR(50) NOT NULL,
                        contact_person_name VARCHAR(150) NOT NULL,
                        primary_phone VARCHAR(20) NOT NULL,
                        alternate_phone VARCHAR(20),
                        email VARCHAR(150),
                        status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                        approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL,
                        PRIMARY KEY (id),
                        CONSTRAINT uk_dealer_user UNIQUE (user_id),
                        CONSTRAINT uk_dealer_code UNIQUE (dealer_code),
                        CONSTRAINT fk_dealer_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_dealer_status ON dealer(status);
CREATE INDEX idx_dealer_approval_status ON dealer(approval_status);
CREATE INDEX idx_dealer_business_type ON dealer(business_type);