CREATE TABLE workshop (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          dealer_id BIGINT NOT NULL,
                          workshop_name VARCHAR(200) NOT NULL,
                          workshop_code VARCHAR(50) NOT NULL,
                          workshop_type VARCHAR(50),
                          contact_person_name VARCHAR(150) NOT NULL,
                          contact_person_designation VARCHAR(100),
                          primary_phone VARCHAR(20) NOT NULL,
                          alternate_phone VARCHAR(20),
                          email VARCHAR(150),
                          floor_area DECIMAL(12,2),
                          floor_area_unit VARCHAR(10),
                          total_labour_count INT,
                          skilled_labour_count INT,
                          unskilled_labour_count INT,
                          supervisor_count INT,
                          working_hours_start TIME,
                          working_hours_end TIME,
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                          approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT uk_workshop_code UNIQUE (workshop_code),
                          CONSTRAINT fk_workshop_dealer FOREIGN KEY (dealer_id) REFERENCES dealer(id)
);

CREATE INDEX idx_workshop_dealer_id ON workshop(dealer_id);
CREATE INDEX idx_workshop_status ON workshop(status);
CREATE INDEX idx_workshop_approval_status ON workshop(approval_status);
CREATE INDEX idx_workshop_type ON workshop(workshop_type);

CREATE TABLE workshop_address (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  workshop_id BIGINT NOT NULL,
                                  address_line_1 VARCHAR(255) NOT NULL,
                                  address_line_2 VARCHAR(255),
                                  area VARCHAR(150),
                                  landmark VARCHAR(150),
                                  city VARCHAR(100) NOT NULL,
                                  district VARCHAR(100),
                                  state VARCHAR(100) NOT NULL,
                                  country VARCHAR(100) NOT NULL,
                                  postal_code VARCHAR(20) NOT NULL,
                                  latitude DECIMAL(10,7),
                                  longitude DECIMAL(10,7),
                                  created_at TIMESTAMP NOT NULL,
                                  updated_at TIMESTAMP NOT NULL,
                                  PRIMARY KEY (id),
                                  CONSTRAINT uk_workshop_address_workshop UNIQUE (workshop_id),
                                  CONSTRAINT fk_workshop_address_workshop FOREIGN KEY (workshop_id) REFERENCES workshop(id)
);

CREATE INDEX idx_workshop_address_city ON workshop_address(city);
CREATE INDEX idx_workshop_address_state ON workshop_address(state);

CREATE TABLE workshop_legal (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                workshop_id BIGINT NOT NULL,
                                gst_number VARCHAR(20),
                                gst_status VARCHAR(20),
                                registration_number VARCHAR(100),
                                registration_type VARCHAR(50),
                                registration_date DATE,
                                license_number VARCHAR(100),
                                license_expiry_date DATE,
                                created_at TIMESTAMP NOT NULL,
                                updated_at TIMESTAMP NOT NULL,
                                PRIMARY KEY (id),
                                CONSTRAINT uk_workshop_legal_workshop UNIQUE (workshop_id),
                                CONSTRAINT uk_workshop_legal_gst UNIQUE (gst_number),
                                CONSTRAINT fk_workshop_legal_workshop FOREIGN KEY (workshop_id) REFERENCES workshop(id)
);

CREATE INDEX idx_workshop_legal_gst_status ON workshop_legal(gst_status);

CREATE TABLE workshop_document (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   workshop_id BIGINT NOT NULL,
                                   document_type VARCHAR(50) NOT NULL,
                                   document_number VARCHAR(100),
                                   document_name VARCHAR(255) NOT NULL,
                                   storage_key VARCHAR(500) NOT NULL,
                                   mime_type VARCHAR(100),
                                   file_size BIGINT,
                                   issue_date DATE,
                                   expiry_date DATE,
                                   verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                   verification_remarks VARCHAR(1000),
                                   verified_by BIGINT,
                                   verified_at TIMESTAMP,
                                   created_at TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP NOT NULL,
                                   PRIMARY KEY (id),
                                   CONSTRAINT fk_workshop_document_workshop FOREIGN KEY (workshop_id) REFERENCES workshop(id)
);

CREATE INDEX idx_workshop_document_workshop_id ON workshop_document(workshop_id);
CREATE INDEX idx_workshop_document_type ON workshop_document(document_type);
CREATE INDEX idx_workshop_document_verification_status ON workshop_document(verification_status);