CREATE TABLE employee (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          user_id BIGINT NOT NULL,
                          employee_code VARCHAR(50) NOT NULL,
                          first_name VARCHAR(100) NOT NULL,
                          middle_name VARCHAR(100),
                          last_name VARCHAR(100),
                          display_name VARCHAR(200) NOT NULL,
                          date_of_birth DATE,
                          gender VARCHAR(20),
                          designation VARCHAR(100) NOT NULL,
                          department VARCHAR(100),
                          employment_type VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
                          joining_date DATE NOT NULL,
                          leaving_date DATE,
                          salary_amount DECIMAL(15,2),
                          salary_currency VARCHAR(10) DEFAULT 'INR',
                          phone VARCHAR(20) NOT NULL,
                          alternate_phone VARCHAR(20),
                          personal_email VARCHAR(150),
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT uk_employee_user UNIQUE (user_id),
                          CONSTRAINT uk_employee_code UNIQUE (employee_code),
                          CONSTRAINT fk_employee_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_employee_status ON employee(status);
CREATE INDEX idx_employee_designation ON employee(designation);
CREATE INDEX idx_employee_department ON employee(department);