CREATE TABLE employee_address (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                  employee_id BIGINT NOT NULL,
                                  address_type VARCHAR(20) NOT NULL,
                                  address_line_1 VARCHAR(255) NOT NULL,
                                  address_line_2 VARCHAR(255),
                                  area VARCHAR(150),
                                  landmark VARCHAR(150),
                                  city VARCHAR(100) NOT NULL,
                                  district VARCHAR(100),
                                  state VARCHAR(100) NOT NULL,
                                  country VARCHAR(100) NOT NULL,
                                  postal_code VARCHAR(20) NOT NULL,
                                  latitude DECIMAL(10,7),
                                  longitude DECIMAL(10,7),
                                  created_at TIMESTAMP NOT NULL,
                                  updated_at TIMESTAMP NOT NULL,
                                  PRIMARY KEY (id),
                                  CONSTRAINT fk_employee_address_employee FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE INDEX idx_employee_address_employee_id ON employee_address(employee_id);
CREATE INDEX idx_employee_address_type ON employee_address(address_type);
CREATE INDEX idx_employee_address_city ON employee_address(city);
CREATE INDEX idx_employee_address_state ON employee_address(state);