CREATE TABLE employee_document (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   employee_id BIGINT NOT NULL,
                                   document_type VARCHAR(50) NOT NULL,
                                   document_number VARCHAR(100),
                                   document_name VARCHAR(255) NOT NULL,
                                   storage_key VARCHAR(500) NOT NULL,
                                   mime_type VARCHAR(100),
                                   file_size BIGINT,
                                   issue_date DATE,
                                   expiry_date DATE,
                                   verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                   verification_remarks VARCHAR(1000),
                                   verified_by BIGINT,
                                   verified_at TIMESTAMP,
                                   created_at TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP NOT NULL,
                                   PRIMARY KEY (id),
                                   CONSTRAINT fk_employee_document_employee
                                       FOREIGN KEY (employee_id) REFERENCES employee(id),
                                   CONSTRAINT fk_employee_document_verified_by
                                       FOREIGN KEY (verified_by) REFERENCES users(id)
);

CREATE INDEX idx_employee_document_employee_id
    ON employee_document(employee_id);

CREATE INDEX idx_employee_document_type
    ON employee_document(document_type);

CREATE INDEX idx_employee_document_verification_status
    ON employee_document(verification_status);

CREATE INDEX idx_employee_document_expiry_date
    ON employee_document(expiry_date);