CREATE TABLE item_type (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           code VARCHAR(50) NOT NULL,
                           name VARCHAR(100) NOT NULL,
                           description VARCHAR(500),
                           active BOOLEAN NOT NULL DEFAULT TRUE,
                           created_at TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP NOT NULL,
                           PRIMARY KEY (id),
                           CONSTRAINT uk_item_type_code UNIQUE (code),
                           CONSTRAINT uk_item_type_name UNIQUE (name)
);

CREATE INDEX idx_item_type_active ON item_type(active);

CREATE TABLE item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      item_type_id BIGINT NOT NULL,
                      item_code VARCHAR(50) NOT NULL,
                      name VARCHAR(200) NOT NULL,
                      description VARCHAR(1000),
                      brand VARCHAR(150),
                      model VARCHAR(150),
                      unit_of_measure VARCHAR(30) NOT NULL,
                      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                      created_at TIMESTAMP NOT NULL,
                      updated_at TIMESTAMP NOT NULL,
                      PRIMARY KEY (id),
                      CONSTRAINT uk_item_code UNIQUE (item_code),
                      CONSTRAINT fk_item_item_type FOREIGN KEY (item_type_id) REFERENCES item_type(id)
);

CREATE INDEX idx_item_item_type_id ON item(item_type_id);
CREATE INDEX idx_item_status ON item(status);
CREATE INDEX idx_item_name ON item(name);


INSERT INTO item_type (code, name, description, created_at, updated_at)
VALUES
    ('STONE', 'Stone', 'Natural and engineered stone materials used for procurement.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('LED', 'LED', 'LED lighting products and components.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PROJECTOR', 'Projector', 'Projectors and related projection equipment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GLASS', 'Glass', 'Glass materials and related products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ELECTRICAL', 'Electrical', 'Electrical components and equipment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ELECTRONIC', 'Electronic', 'Electronic components and equipment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MECHANICAL', 'Mechanical', 'Mechanical components and equipment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('FINISHING_MATERIAL', 'Finishing Material', 'Materials used for finishing and surface treatment.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PACKAGING_MATERIAL', 'Packaging Material', 'Materials used for packaging and transportation.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('OTHER', 'Other', 'Other procurement items that do not fit existing categories.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);